:- dynamic(graduation_course/2).
graduation_course('Ciencia da Computacao', 'DCC160').
graduation_course('Ciencia da Computacao', 'MAT155').
graduation_course('Ciencia da Computacao', 'MAT154').
graduation_course('Ciencia da Computacao', 'DCC179').
graduation_course('Ciencia da Computacao', 'DCC119').
graduation_course('Ciencia da Computacao', 'DCC120').
graduation_course('Ciencia da Computacao', 'DCC175').
graduation_course('Ciencia da Computacao', 'DCC158').
graduation_course('Ciencia da Computacao', 'MAT156').
graduation_course('Ciencia da Computacao', 'FIS073').
graduation_course('Ciencia da Computacao', 'FIS077').
graduation_course('Ciencia da Computacao', 'DCC013').
graduation_course('Ciencia da Computacao', 'DCC107').
graduation_course('Ciencia da Computacao', 'MAT143').
graduation_course('Ciencia da Computacao', 'MAT157').
graduation_course('Ciencia da Computacao', 'DCC059').
graduation_course('Ciencia da Computacao', 'DCC122').
graduation_course('Ciencia da Computacao', 'DCC025').
graduation_course('Ciencia da Computacao', 'EADDCC044').
graduation_course('Ciencia da Computacao', 'MAT029').
graduation_course('Ciencia da Computacao', 'EST028').
graduation_course('Ciencia da Computacao', 'DCC070').
graduation_course('Ciencia da Computacao', 'DCC012').
graduation_course('Ciencia da Computacao', 'DCC117').
graduation_course('Ciencia da Computacao', 'EST029').
graduation_course('Ciencia da Computacao', 'DCC014').
graduation_course('Ciencia da Computacao', 'DCC062').
graduation_course('Ciencia da Computacao', 'DCC060').
graduation_course('Ciencia da Computacao', 'DCC061').
graduation_course('Ciencia da Computacao', 'DCC163').
graduation_course('Ciencia da Computacao', 'DCC063').
graduation_course('Ciencia da Computacao', 'DCC042').
graduation_course('Ciencia da Computacao', 'DCC008').
graduation_course('Ciencia da Computacao', 'DCC174').
graduation_course('Ciencia da Computacao', 'DCC075').
graduation_course('Ciencia da Computacao', 'DCC055').
graduation_course('Ciencia da Computacao', 'DCC001').
graduation_course('Ciencia da Computacao', 'DCC065').
graduation_course('Ciencia da Computacao', 'DCC019').
graduation_course('Ciencia da Computacao', 'DCC045').
graduation_course('Ciencia da Computacao', 'DCC064').
graduation_course('Ciencia da Computacao', 'DCC123').
graduation_course('Ciencia da Computacao', 'DCC110').

graduation_course('Sistema de Informacao', 'MAT154').
graduation_course('Sistema de Informacao', 'MAT155').
graduation_course('Sistema de Informacao', 'DCC119').
graduation_course('Sistema de Informacao', 'DCC120').
graduation_course('Sistema de Informacao', 'DCC160').
graduation_course('Sistema de Informacao', 'DCC133').
graduation_course('Sistema de Informacao', 'MAT156').
graduation_course('Sistema de Informacao', 'DCC121').
graduation_course('Sistema de Informacao', 'DCC013').
graduation_course('Sistema de Informacao', 'DCC107').
graduation_course('Sistema de Informacao', 'CAD076').
graduation_course('Sistema de Informacao', 'EADDCC049').
graduation_course('Sistema de Informacao', 'EST029').
graduation_course('Sistema de Informacao', 'DCC025').
graduation_course('Sistema de Informacao', 'DCC059').
graduation_course('Sistema de Informacao', 'FIN001').
graduation_course('Sistema de Informacao', 'EADDCC044').
graduation_course('Sistema de Informacao', 'DCC070').
graduation_course('Sistema de Informacao', 'DCC117').
graduation_course('Sistema de Informacao', 'DCC146').
graduation_course('Sistema de Informacao', 'DCC012').
graduation_course('Sistema de Informacao', 'DCC062').
graduation_course('Sistema de Informacao', 'DCC014').
graduation_course('Sistema de Informacao', 'DCC061').
graduation_course('Sistema de Informacao', 'DCC060').
graduation_course('Sistema de Informacao', 'DCC192').
graduation_course('Sistema de Informacao', 'DCC042').
graduation_course('Sistema de Informacao', 'DCC163').
graduation_course('Sistema de Informacao', 'DCC174').
graduation_course('Sistema de Informacao', 'DCC193').
graduation_course('Sistema de Informacao', 'DCC049').
graduation_course('Sistema de Informacao', 'DCC154').
graduation_course('Sistema de Informacao', 'DCC168').
graduation_course('Sistema de Informacao', 'DCC078').
graduation_course('Sistema de Informacao', 'DCC077').
graduation_course('Sistema de Informacao', 'DCC145').
graduation_course('Sistema de Informacao', 'DCC196').
graduation_course('Sistema de Informacao', 'DCC166').
graduation_course('Sistema de Informacao', 'DCC165').
graduation_course('Sistema de Informacao', 'DCC123').
graduation_course('Sistema de Informacao', 'DCC194').