:- dynamic(student_graduation/2).
student_graduation('Andre', 'Ciencia da Computacao').
student_graduation('Bernardo', 'Ciencia da Computacao').
student_graduation('Jose', 'Ciencia da Computacao').
student_graduation('Julia', 'Ciencia da Computacao').
student_graduation('Cristina', 'Ciencia da Computacao').
student_graduation('Pedro', 'Ciencia da Computacao').
student_graduation('Lucas', 'Ciencia da Computacao').
student_graduation('Ana', 'Ciencia da Computacao').
student_graduation('Catarina', 'Ciencia da Computacao').
student_graduation('Joao', 'Ciencia da Computacao').
student_graduation('Mariana', 'Sistema de Informacao').
student_graduation('Paulo', 'Sistema de Informacao').
student_graduation('Carlos', 'Sistema de Informacao').
student_graduation('Clara', 'Sistema de Informacao').
student_graduation('Thales', 'Sistema de Informacao').
student_graduation('Thalita', 'Sistema de Informacao').
student_graduation('Leonardo', 'Sistema de Informacao').
student_graduation('Breno', 'Sistema de Informacao').
student_graduation('Flavia', 'Sistema de Informacao').
student_graduation('Matheus', 'Sistema de Informacao').