:- dynamic(student/1).
student('Andre').
student('Bernardo').
student('Jose').
student('Julia').
student('Cristina').
student('Pedro').
student('Lucas').
student('Ana').
student('Catarina').
student('Joao').
student('Mariana').
student('Paulo').
student('Carlos').
student('Clara').
student('Thales').
student('Thalita').
student('Leonardo').
student('Breno').
student('Flavia').
student('Matheus'). 